FROM apache/airflow:2.10.5-python3.11

# Switch to root to perform a global system installation
USER airflow

# Upgrade pip and install the full package globally 
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir "acryl-datahub[datahub]"
