pipeline_name: Instance1_FEDE_Pipeline
datahub_api:
  server: "http://datahub-gms-1:8080"
  token: "JohnSnowKnowsNothingAboutCryptography"
source:
  type: datahub
  config:
    include_all_versions: false
    database_connection:
      scheme: "mysql+pymysql"
      host_port: "mysql-1:3306"
      username: datahub
      password: datahub
      database: datahub
    kafka_connection:
      bootstrap: "broker-1:29092"
      schema_registry_url: "http://schema-registry-1:8081"
    stateful_ingestion:
      enabled: true
      ignore_old_state: false
    urn_pattern:
      deny:
        - "^urn:li:dataHubPageModule.*"
        - "^urn:li:dataHubIngestionSource.*"
        - "^urn:li:dataHubExecutionRequest.*"
        - "^urn:li:dataHubSecret.*"
        - "^urn:li:dataHubAccessToken.*"
        - "^urn:li:inviteToken.*"
        - "^urn:li:globalSettings.*"
        - "^urn:li:dataHubStepState.*"
flags:
  set_system_metadata: false
sink:
  type: datahub-rest
  config:
    server: "http://datahub-gms-fede:8080"
    token: "JohnSnowKnowsNothingAboutCryptography"
