FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install \
        'acryl-datahub[iceberg]>=0.14.0' \
        'pyiceberg[nessie,pyarrow]>=0.8.0'

RUN mkdir -p /etc/recipes

ENTRYPOINT ["datahub"]