#!/bin/bash
# =============================================================================
# ingest.sh — Automated DataHub Iceberg Ingestion
#
# What it does:
#   1. Authenticates with user/password and generates a fresh PAT
#   2. Upserts the token into the datahub-token K8s secret
#   3. Re-runs the Kubernetes ingestion job
#   4. Tails the job logs
#
# Usage:
#   ./ingest.sh [OPTIONS]
#
# Options:
#   -u <username>     DataHub username  (default: datahub)
#   -p <password>     DataHub password  (default: datahub)
#   -n <namespace>    K8s namespace     (default: datahub1)
#   -d <days>         Token TTL in days (default: 30)
#   -l <local_port>   Local port for GMS port-forward (default: 8080)
#   -s                Skip token rotation (reuse existing secret)
#   -h                Show this help
#
# Examples:
#   ./ingest.sh
#   ./ingest.sh -u datahub -p mysecret -d 7
#   ./ingest.sh -s          # skip token rotation, just rerun the job
# =============================================================================
set -euo pipefail

# --------------------------------------------------------------------------- #
# Defaults
# --------------------------------------------------------------------------- #
DH_USER="datahub"
DH_PASS="datahub"
NAMESPACE="datahub1"
TOKEN_TTL_DAYS=30
LOCAL_PORT=8080
SKIP_TOKEN=false
GMS_SVC="datahub-datahub-gms"
JOB_NAME="iceberg-ingestion-job"
CONFIGMAP_NAME="iceberg-recipe"
SECRET_NAME="datahub-token"

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
ok()   { echo "[$(date '+%H:%M:%S')] ✓  $*"; }
err()  { echo "[$(date '+%H:%M:%S')] ✗  $*" >&2; }
die()  { err "$*"; exit 1; }

usage() {
    grep '^#' "$0" | grep -v '^#!/' | sed 's/^# \?//'
    exit 0
}

# --------------------------------------------------------------------------- #
# Parse arguments
# --------------------------------------------------------------------------- #
while getopts "u:p:n:d:l:sh" opt; do
    case "$opt" in
        u) DH_USER="$OPTARG" ;;
        p) DH_PASS="$OPTARG" ;;
        n) NAMESPACE="$OPTARG" ;;
        d) TOKEN_TTL_DAYS="$OPTARG" ;;
        l) LOCAL_PORT="$OPTARG" ;;
        s) SKIP_TOKEN=true ;;
        h) usage ;;
        *) die "Unknown option. Use -h for help." ;;
    esac
done

# --------------------------------------------------------------------------- #
# Pre-flight checks
# --------------------------------------------------------------------------- #
for cmd in kubectl curl jq; do
    command -v "$cmd" >/dev/null 2>&1 || die "'$cmd' is not installed or not in PATH"
done

kubectl get namespace "$NAMESPACE" >/dev/null 2>&1 \
    || die "Namespace '$NAMESPACE' not found. Is your minikube running?"

GMS_URL="http://localhost:${LOCAL_PORT}"
TOKEN_TTL_MS=$(( TOKEN_TTL_DAYS * 86400 * 1000 ))



# --------------------------------------------------------------------------- #
# Step 1 — Authenticate and generate a Personal Access Token
# --------------------------------------------------------------------------- #
generate_token() {
    log "Fetching System Credentials from Kubernetes..."
    
    # Try to get the ID, default to "datahub" if the key is missing
    SYSTEM_ID=$(kubectl get secret datahub-auth-secrets -n "$NAMESPACE" -o jsonpath='{.data.system_client_id}' 2>/dev/null | base64 --decode || echo "datahub")
    
    # Fetch the secret
    SYSTEM_SECRET=$(kubectl get secret datahub-auth-secrets -n "$NAMESPACE" -o jsonpath='{.data.system_client_secret}' 2>/dev/null | base64 --decode || echo "")

    if [[ -z "$SYSTEM_SECRET" ]]; then
        die "Could not find 'system_client_secret' in K8s secret 'datahub-auth-secrets'. Check your secret keys."
    fi

    log "Generating Personal Access Token for '${DH_USER}' (System ID: ${SYSTEM_ID})..."

    # Request the PAT
    local token_response
    token_response=$(curl -sf \
        -X POST \
        -H "Content-Type: application/json" \
        -H "Authorization: Basic $(echo -n "${SYSTEM_ID}:${SYSTEM_SECRET}" | base64)" \
        -d "{
            \"type\": \"PERSONAL\",
            \"actorUrn\": \"urn:li:corpuser:${DH_USER}\",
            \"duration\": ${TOKEN_TTL_MS},
            \"name\": \"ingest-auto-$(date +%Y%m%d)\",
            \"description\": \"Auto-generated by ingest.sh\"
        }" \
        "${GMS_URL}/api/v1/auth/generateAccessToken") \
        || die "Token generation failed. Ensure GMS is up and the system credentials match GMS configuration."

    NEW_TOKEN=$(echo "$token_response" | jq -r '.accessToken // empty')
    
    [[ -z "$NEW_TOKEN" ]] && die "Could not extract accessToken from response: ${token_response}"

    ok "PAT generated successfully"
}

# --------------------------------------------------------------------------- #
# Step 2 — Upsert the token into the K8s secret
# --------------------------------------------------------------------------- #
update_secret() {
    log "Updating K8s secret '${SECRET_NAME}' in namespace '${NAMESPACE}'..."

    kubectl create secret generic "$SECRET_NAME" \
        --from-literal=token="$NEW_TOKEN" \
        -n "$NAMESPACE" \
        --dry-run=client -o yaml \
    | kubectl apply -f -

    ok "Secret '${SECRET_NAME}' updated"
}

# --------------------------------------------------------------------------- #
# Step 3 — Re-run the ingestion job
# --------------------------------------------------------------------------- #
run_ingestion_job() {
    log "Cleaning up previous job and configmap..."
    kubectl delete job/"${JOB_NAME}"     -n "$NAMESPACE" --ignore-not-found
    kubectl delete configmap/"${CONFIGMAP_NAME}" -n "$NAMESPACE" --ignore-not-found
    sleep 2

    log "Applying ingestion manifests..."
    kubectl apply -f iceberg_ingestion.yaml
    kubectl apply -f iceberg_ingestion_job.yaml
    ok "Job '${JOB_NAME}' submitted"
}

# --------------------------------------------------------------------------- #
# Step 4 — Wait for the job pod to be ready and tail logs
# --------------------------------------------------------------------------- #
follow_logs() {
    log "Waiting for job pod to start..."
    local max_wait=120
    local waited=0

    until kubectl get pods \
        -n "$NAMESPACE" \
        -l "job-name=${JOB_NAME}" \
        --no-headers 2>/dev/null \
        | grep -qE "(Running|Completed|Error)"; do
        sleep 2
        (( waited+=2 ))
        [[ $waited -ge $max_wait ]] && {
            err "Pod did not start after ${max_wait}s. Showing job events:"
            kubectl describe job/"${JOB_NAME}" -n "$NAMESPACE" | tail -20
            exit 1
        }
    done

    ok "Pod running — following logs (Ctrl+C to detach):"
    echo "─────────────────────────────────────────────"
    kubectl logs "job/${JOB_NAME}" -n "$NAMESPACE" --follow --all-containers=true

    # Final status check
    echo "─────────────────────────────────────────────"
    local exit_code
    exit_code=$(kubectl get job/"${JOB_NAME}" -n "$NAMESPACE" \
        -o jsonpath='{.status.conditions[0].type}' 2>/dev/null || echo "Unknown")

    if [[ "$exit_code" == "Complete" ]]; then
        ok "Ingestion job completed successfully"
    else
        err "Job ended with status: ${exit_code}"
        kubectl describe job/"${JOB_NAME}" -n "$NAMESPACE" | tail -20
        exit 1
    fi
}

# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
echo "=============================================="
echo "  DataHub Iceberg Ingestion — Auto Runner"
echo "  Namespace : ${NAMESPACE}"
echo "  GMS port  : ${LOCAL_PORT}"
echo "  Token TTL : ${TOKEN_TTL_DAYS} days"
echo "  Skip token: ${SKIP_TOKEN}"
echo "=============================================="
echo

if [[ "$SKIP_TOKEN" == false ]]; then
    generate_token
    update_secret
else
    log "Skipping token rotation (-s flag set)"
fi

run_ingestion_job
follow_logs
