apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: datahub1
  labels:
    app: nessie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.79.0
          ports:
            - containerPort: 19120
              name: http
          env:
            # Tipus de magatzem per a metadades (branques, commits)
          - name: NESSIE_CATALOG_ENABLED
            value: "true"
          - name: NESSIE_CATALOG_DEFAULT_WAREHOUSE
            value: "default"
          - name: NESSIE_CATALOG_WAREHOUSES_DEFAULT_LOCATION
            value: "file:///home/ibdn/TFM/iceberg_warehouse"
          - name: QUARKUS_PROFILE
            value: "prod"
          - name: NESSIE_VERSION_STORE_TYPE
            value: "IN_MEMORY"
          volumeMounts:
            - name: warehouse-volume
              mountPath: /home/ibdn/TFM/iceberg_warehouse
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/v2/config
            port: 19120
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/v2/config
            port: 19120
          initialDelaySeconds: 30
          periodSeconds: 10
        volumes:
          - name: warehouse-volume
            hostPath:
              path: /mnt/tfm # ruta del directori de la makina de minikube, no el host local.
              type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nessie-service
  namespace: datahub1
spec:
  type: ClusterIP
  selector:
    app: nessie
  ports:
    - protocol: TCP
      port: 19120
      targetPort: 19120
      name: http