apiVersion: v1
kind: Secret
metadata:
  name: datahub-token
  namespace: datahub1
type: Opaque
stringData:
  token: "eyJhbGciOiJIUzI1NiJ9.eyJhY3RvclR5cGUiOiJVU0VSIiwiYWN0b3JJZCI6ImRhdGFodWIiLCJ0eXBlIjoiUEVSU09OQUwiLCJ2ZXJzaW9uIjoiMiIsImp0aSI6IjQ0Y2M4MjkzLTMxNmQtNDM1NC1hYmY4LTY2NGFlYmNiM2M1YiIsInN1YiI6ImRhdGFodWIiLCJleHAiOjE3ODM3Nzc3NDMsImlzcyI6ImRhdGFodWItbWV0YWRhdGEtc2VydmljZSJ9.1GROMBLjrEsSBSm1XEpZdiDL7SbPe8eBRe-R0nJa8og"
